name: Build and Deploy Converter

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: .\installResources.ps1

    - name: Build executable
      run: |
        pyinstaller --onefile --name konwerter main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: konwerter-exe
        path: dist/konwerter.exe

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: konwerter-exe

    - name: Create tag
      run: |
        TAG="release-$(date +'%Y%m%d-%H%M%S')"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git tag $TAG ${{ github.sha }}
        git push origin $TAG

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.Create_tag.outputs.tag }}
        files: konwerter.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
